import {
  AlertTriangleIcon,
  BarChart3Icon,
  BellIcon,
  CalendarClockIcon,
  ClipboardCheckIcon,
  ClockIcon,
  FileSignatureIcon,
  FileTextIcon,
  FilterIcon,
  FlaskConicalIcon,
  GaugeIcon,
  KanbanSquareIcon,
  LayoutDashboardIcon,
  LayoutTemplateIcon,
  MailIcon,
  SendIcon,
  SettingsIcon,
  TimerIcon,
  UserIcon,
  UsersIcon,
  UsersRoundIcon,
  type LucideIcon,
} from "lucide-react";

/** Resolves the string icon names used in navigation.config to components. */
export const NAV_ICONS: Record<string, LucideIcon> = {
  AlertTriangle: AlertTriangleIcon,
  BarChart3: BarChart3Icon,
  Bell: BellIcon,
  CalendarClock: CalendarClockIcon,
  ClipboardCheck: ClipboardCheckIcon,
  Clock: ClockIcon,
  FileSignature: FileSignatureIcon,
  FileText: FileTextIcon,
  Filter: FilterIcon,
  FlaskConical: FlaskConicalIcon,
  Gauge: GaugeIcon,
  KanbanSquare: KanbanSquareIcon,
  LayoutDashboard: LayoutDashboardIcon,
  LayoutTemplate: LayoutTemplateIcon,
  Mail: MailIcon,
  Send: SendIcon,
  Settings: SettingsIcon,
  Timer: TimerIcon,
  User: UserIcon,
  Users: UsersIcon,
  UsersRound: UsersRoundIcon,
};
